name: 'my_new_project'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "CREATE TABLE IF NOT EXISTS monitoring.audit_log ( model_name STRING, status STRING, started_at TIMESTAMP, finished_at TIMESTAMP, duration_seconds FLOAT64 )"
  - "CREATE TABLE IF NOT EXISTS monitoring.details_execution (model_name STRING, status STRING, started_at TIMESTAMP, finished_at TIMESTAMP, duration_seconds FLOAT64, run_id STRING, environment STRING, user STRING, project_name STRING, models_success INT64, models_failed INT64, total_models INT64, execution_status STRING, error_message STRING)"

on-run-end:
  - "{{ notify_run_end() }}"

models:
  my_new_project:
    staging:
      +schema: dbt_staging
      +enabled: true
      +materialized: table
      +pre-hook:
        - "INSERT INTO monitoring.audit_log VALUES ('{{ this }}','started', CURRENT_TIMESTAMP(), NULL, NULL)"
      +post-hook:
        - "UPDATE monitoring.audit_log SET status='completed', finished_at=CURRENT_TIMESTAMP(), duration_seconds=TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), started_at, SECOND) WHERE model_name='{{ this }}' AND finished_at IS NULL"

    warhouse:
      +schema: dbt_warehouse
      +enabled: true
      +materialized: table
      
      dim_date:
        +materialized: view
        +post-hook:
          - "INSERT INTO monitoring.audit_log VALUES ('{{ this }}','started', CURRENT_TIMESTAMP(), NULL, NULL)"

  elementary:
    +schema: elementary

tests:
  my_new_project:
    +severity: warn

flags:
  require_generic_test_arguments_property: true
