name: DBT CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Installer DBT et dépendances
      - name: Install DBT
        run: |
          pip install dbt-core dbt-bigquery  # ou dbt-postgres selon ton profil

      - name: Run dbt test
        run: dbt test --profiles-dir ./
        
      - name: dbt run
        run: dbt run --profiles-dir ./    
