name: DBT CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Installer DBT et dépendances
      - name: Install DBT
        run: |
          pip install dbt-core dbt-bigquery  # ou dbt-postgres selon ton profil

      # 4️⃣ Copier le fichier profiles.yml dans ~/.dbt pour que DBT le trouve
      - name: Setup DBT profiles
        run: |
          mkdir -p ~/.dbt
          cp ./profiles.yml ~/.dbt/profiles.yml

      # 5️⃣ Vérifier le projet (compile)
      - name: DBT Compile
        run: dbt compile

      # 6️⃣ Exécuter les seeds
      - name: DBT Seed
        run: dbt seed

      # 7️⃣ Exécuter les tests sur le target CI
      - name: DBT Test
        run: dbt test --target ci
