name: dbt CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt BigQuery
        run: pip install dbt-bigquery

      - name: Configure GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > ${HOME}/gcp_credentials.json

      - name: Set up profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "
          my_project:
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: <TON_PROJECT_ID>
                dataset: dbt_ci
                keyfile: ${HOME}/gcp_credentials.json
            target: dev
          " > ~/.dbt/profiles.yml

      - name: Install dependencies
        run: dbt deps

      - name: Run dbt compile
        run: dbt compile --profiles-dir .

      - name: Run dbt tests
        run: dbt test --profiles-dir .
