name: DBT CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      #  Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      #  Installer Python et dbt BigQuery
      - name: Setup Python and dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery


      #  Vérifier la connexion à BigQuery
      - name: dbt debug
        run: dbt debug --profiles-dir ./ --profile my_new_project
        
      #  Lancer dbt run et test
      - name: dbt run
        run: dbt run --profiles-dir ./

      - name: dbt test
        run: dbt test --profiles-dir ./
